# Generated by Django 4.1 on 2024-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_ticket_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('cargo', 'seats'), name='unique_cargo_seat'),
        ),
    ]
