# Generated by Django 4.1 on 2024-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_ticket_unique_cargo_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintype',
            name='image',
            field=models.ImageField(blank=True, upload_to='train_types'),
        ),
    ]
