# Generated by Django 4.1 on 2024-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_traintype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintype',
            name='image',
            field=models.ImageField(upload_to='train_types'),
        ),
    ]
